feat(TaskPageSprintfilter): Add changeSprint functionality to Task Pa…
Worktez/worktez pull request #259
Opened 2021-09-12 18:58 UTC by Akshay-Jak

…ge directly

Signed-off-by: Akshay <akshayjani2147@gmail.com>

### Functionality:
A function to change the sprint directly from the Task Page instead of going back to Board page and change

### Solution:
Made a function changeSprint to filter between sprints

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start

2021-09-13 13:04 UTC, arjund-06 requested changes
Make the following changes

2021-09-13 13:04 UTC, arjund-06 commented on src/app/body/tasks/tasks.component.ts
> +
Remove the unnecessary empty lines

2021-09-13 13:04 UTC, arjund-06 commented on src/app/body/tasks/tasks.component.ts
> +      console.log(2);
Remove the console.logs

2021-09-13 18:53 UTC, arjund-06 approved these changes
Ship it

2021-09-15 13:36 UTC, viv9k requested changes
Please do the required changes

2021-09-15 13:36 UTC, viv9k commented on src/app/body/tasks/tasks.component.html
> +
Let's have this input box inside filter list and also rearrange the list horizontally.

2021-09-18 06:15 UTC, viv9k requested changes
Please do the required changes

2021-09-18 06:15 UTC, viv9k commented on src/app/body/tasks/tasks.component.ts
> +      this.currentSprintName = this.fullSprintName(newSprintNumber);
I don't think we are using backlog in link when somebody goes to backlog and same with deleted. So better we keep the number only

2021-09-18 08:33 UTC, viv9k approved these changes
ship it

2021-09-18 08:55 UTC, merged