feat(dev/Assignee) : create new task bug
Worktez/worktez pull request #260
Opened 2021-09-13 14:21 UTC by Pendyala-thanvi

### Functionality:
Create new task email input

### Solution:
Let's user give an email that is not present in datalist too.

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
ng serve
firebase emulators:start

2021-09-15 13:51 UTC, viv9k requested changes
Please do the required changes

2021-09-15 13:51 UTC, viv9k commented on src/app/services/tool/tools.service.ts
> +   }
You can put this regx into validation service and from there we can validate email.

2021-09-16 15:26 UTC, k0malSharma requested changes
Please do the required changes

2021-09-16 15:26 UTC, k0malSharma commented on src/app/services/tool/tools.service.ts
> +  getEmailString(email: any){
The assignee name is of type string

2021-09-17 15:00 UTC, k0malSharma requested changes

2021-09-17 15:00 UTC, k0malSharma commented on src/app/services/tool/tools.service.ts
> +    let startindex = email.indexOf('<')
indexof() will not work on undefined values. So first check if email is undefined and return before performing indexOf().

2021-09-18 12:37 UTC, k0malSharma approved these changes
Ship it

2021-09-18 13:53 UTC, viv9k approved these changes
Ship it

2021-09-18 13:58 UTC, merged