feat(List Patches): Added Page to List Patches.
Worktez/worktez pull request #262
Opened 2021-09-15 11:39 UTC by deeptea22

### Functionality:
A page to display all the patches.

### Solution:
Added 3 components to list patches.

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start

2021-09-16 09:16 UTC, shivamgoyal7 approved these changes
Ship it

2021-09-18 06:26 UTC, viv9k requested changes
please do the required.

2021-09-18 06:26 UTC, viv9k commented on src/app/list-patches/edit-patch/edit-patch.component.ts
> +      this.showClose = true;
Inappropriate way to call api, This doesn't explain things properly

2021-09-18 06:26 UTC, viv9k commented on src/app/list-patches/edit-patch/edit-patch.component.ts
> +  }
This  doesn't explain why we have such an algorithm

2021-09-18 06:26 UTC, viv9k commented on src/app/list-patches/edit-patch/edit-patch.component.ts
> +    });
Not a right way to handle data.

2021-09-18 06:26 UTC, viv9k commented on src/app/list-patches/edit-patch/edit-patch.component.ts
> +    });
Check other places how it's done.

2021-09-18 06:26 UTC, viv9k commented on src/app/list-patches/patch-cards/patch-cards.component.ts
> +  }
The edit patch isn't that good

2021-09-19 18:06 UTC, closed without merging