feat(List Patches): Added Page to List Patches.
Worktez/worktez pull request #268
Opened 2021-09-19 18:34 UTC by deeptea22

### Functionality:
A page to display all the patches.

### Solution:
Added 3 components to list patches.

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start
move to /ListPatches

2021-09-19 18:34 UTC, deeptea22 commented
Have resolved all the changes requested in the previous pull request.

2021-09-21 11:26 UTC, arjund-06 requested changes

2021-09-21 11:26 UTC, arjund-06 commented on functions/model/patch/editPatch.js
> +    const PatchId = request.body.data.Id;
It would be better to use camelCasing

2021-09-21 11:26 UTC, arjund-06 commented on functions/model/patch/patch.js
> +            console.log("edit");
Remove this log

2021-09-21 11:26 UTC, arjund-06 commented on src/app/list-patches/edit-patch/edit-patch.component.ts
> +  }
This can be one single function I guess

2021-09-21 12:45 UTC, viv9k approved these changes
Ship it

2021-09-21 13:05 UTC, merged