Type field
Worktez/worktez pull request #270
Opened 2021-09-20 15:59 UTC by Akshay-Jak

### Functionality:
Added a New Field called Type

### Solution:
Added a new field Type to know the type of the task that is being assigned

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start

2021-09-22 10:29 UTC, viv9k requested changes
Please do the required changes

2021-09-22 10:29 UTC, viv9k commented on src/app/body/create-new-session/create-new-session.component.html
> +                        </datalist>
Make this list dynamic like others

2021-09-22 12:31 UTC, k0malSharma commented
Resolve merge conflict in _**functions/model/tasks/createTask.js**_ as well

2021-09-24 13:06 UTC, viv9k requested changes
At some places I see label and at some places it's type.

Use one everywhere, best convert everything to type.

2021-09-28 06:36 UTC, viv9k approved these changes
Ship it

2021-09-28 12:17 UTC, merged