Dev/editpageUI : UI changes in edit page
Worktez/worktez pull request #318
Opened 2021-10-26 18:31 UTC by Pendyala-thanvi

### Functionality:
edit page

### Solution:
new UI changes

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start

2021-10-31 03:26 UTC, k0malSharma requested changes

2021-10-31 03:26 UTC, k0malSharma commented on src/app/body/task-details/edit-page/edit-page.component.html
> +        <div class="row modal-content">
Don't add row with modal content. Let them be in separate div.

2021-10-31 03:26 UTC, k0malSharma commented on src/app/body/task-details/edit-page/edit-page.component.html
> +                    <span class="pl-3" style="color: var(--text);">{{ todayDate }}</span>
Don't  apply the color style here

2021-10-31 03:26 UTC, k0malSharma commented on src/app/body/task-details/log-work/log-work.component.html
> +        <div class="row modal-content">
Do not apply row with modal content. Use different div for both

2021-11-02 11:40 UTC, viv9k approved these changes
Approved

2021-11-02 15:45 UTC, merged