Pop/up
Worktez/worktez pull request #362
Opened 2022-01-01 09:14 UTC by Akshay-Jak

### Functionality:
Improved Pop-Up alerts

### Solution:
Improved pop-up alerts for log-work, edit-task and edit functions in the profile component

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start

![Screenshot (26)](https://user-images.githubusercontent.com/68271366/147847611-49d0b2f7-bbf0-4ffd-b9d1-7997ae071c83.png)

2022-01-02 04:17 UTC, viv9k requested changes
Please do the required changes and update

2022-01-02 04:17 UTC, viv9k commented on src/app/body/profile/edit-profile/edit-profile.component.html
> +                    <div class="row"></div>
what is this row?

2022-01-02 04:17 UTC, viv9k commented on src/app/body/profile/edit-projects/edit-projects.component.html
> +                    <div class="row"></div>
Please remove this extra row

2022-01-03 14:06 UTC, Akshay-Jak commented on src/app/body/profile/edit-projects/edit-projects.component.html
> +                    <div class="row"></div>
removed extra rows

2022-01-03 15:06 UTC, k0malSharma commented on src/app/body/profile/edit-profile/edit-profile.component.html
> +                    <!-- <div class="row"></div> -->
Remove Comment

2022-01-03 16:57 UTC, viv9k commented
This branch can we merged after my footer changes

2022-01-03 17:24 UTC, viv9k approved these changes
Approved

2022-01-03 17:33 UTC, merged