feat(remainingUIMigration): Completed the remaining UI Migration
Worktez/worktez pull request #373
Opened 2022-01-11 14:25 UTC by sid-bagwe

### Functionality:
Completed the remaining UI: create new team, update team and create new organization pages.

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start
Go to the my organization page check the create team and update team pop-up modals

2022-01-12 11:25 UTC, viv9k approved these changes
Approved

2022-01-13 15:27 UTC, k0malSharma requested changes
Balance the col in html files so that they add up to 12

2022-01-13 15:27 UTC, k0malSharma commented on src/app/body/create-new-organization/create-new-organization.component.html
> +                    <!-- <div class="form-group row pt-2">
Remove the comment

2022-01-15 04:54 UTC, k0malSharma approved these changes
Approved

2022-01-16 13:07 UTC, merged