fix(deleteFile): fixed delete file
Worktez/worktez pull request #391
Opened 2022-01-22 14:49 UTC by simran142002

### Functionality:
Users can now delete files in organisation page

### Solution:
made a separate method for delete and created the api file for it

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
1)ng serve
2)firebase emulators:start
3)worktez.com
4)my organization
5)document
6)upload and delete file

2022-01-22 15:19 UTC, viv9k requested changes
Please connect over it for more clarity

2022-01-22 15:19 UTC, viv9k commented on functions/model/librarian/tark/deleteFilesInOrg.js
> +      const promise1 = getOrg(orgDomain).then((orgDoc) => {
I didn't get it we are getting org multiple times

2022-01-22 15:22 UTC, Pendyala-thanvi reviewed
Do the mentioned changes.

2022-01-22 15:22 UTC, Pendyala-thanvi commented on functions/model/librarian/tark/deleteFilesInOrg.js
> +const { updateFileToOrg } = require("../lib")
const { updateFileToOrg } = require("../lib"). This statement is written twice. Remove one.

2022-01-22 15:22 UTC, Pendyala-thanvi commented on functions/model/librarian/tark/deleteFilesInOrg.js
> +const { getOrg } = require("../../organization/lib");
getOrg, updateOrg, and getOrgUseAppKey are from a single file. get them all at once.

2022-01-24 13:22 UTC, Pendyala-thanvi reviewed
resolve merge conflicts.

2022-01-25 15:30 UTC, viv9k commented
Merge conflict not resolved properly and the delete fix was having all the changes from previous release

2022-01-27 04:09 UTC, closed without merging