fix(github-integration-api-trigger): "fixed github integration api link"
Worktez/worktez pull request #501
Opened 2022-03-30 17:56 UTC by abhishek-mishra019

Signed-off-by: Abhishek Mishra <am1426620@gmail.com>

### Functionality:
fix github integration

### Solution:
fixed Github integration API trigger

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
on my Organisation page, click integrate GitHub for a team .

2022-04-01 08:40 UTC, printf-twinkle requested changes

2022-04-01 08:40 UTC, printf-twinkle commented on src/app/services/http-service.service.ts
>      console.log("the url:", url);
remove this console

2022-04-01 15:29 UTC, abhishek-mishra019 commented on src/app/services/http-service.service.ts
>      console.log("the url:", url);
done

2022-04-02 16:05 UTC, viv9k approved these changes
Approved

2022-04-02 16:06 UTC, merged