fix/footer
Worktez/worktez pull request #546
Opened 2022-04-25 15:17 UTC by ponrajaprabhusk

### Functionality:
fixed the footer in homepage

### Solution:

### Risk level:
- [ ] high 
- [ ] medium
- [X] low

### How to test:
<-- please tell us how to test functionality/bug -->

2022-04-27 11:05 UTC, Pendyala-thanvi commented
@ponrajaprabhusk fill the **solution** and **how to fix** section

2022-04-27 19:26 UTC, printf-twinkle reviewed
Fixes

2022-04-27 19:26 UTC, printf-twinkle commented on functions/model/contributors/lib.js
> +    console.log(about);
remove this console log

2022-04-27 19:26 UTC, printf-twinkle commented on functions/model/contributors/tark/addContributor.js
> +    console.log(about);
remove this console log

2022-04-28 14:53 UTC, ponrajaprabhusk commented on functions/model/contributors/lib.js
> +    console.log(about);
Done!

2022-04-28 14:53 UTC, ponrajaprabhusk commented on functions/model/contributors/tark/addContributor.js
> +    console.log(about);
Done

2022-04-28 14:54 UTC, ponrajaprabhusk commented
> 

D

2022-04-30 09:02 UTC, viv9k requested changes
Please revert the unnecessary changes

2022-04-30 09:02 UTC, viv9k commented on functions/package-lock.json
> -        "firebase-admin": "^10.0.2",
Revert the changes in this file

2022-04-30 09:02 UTC, viv9k commented on functions/package.json
> +    "firebase-functions": "^3.19.0"
revert this file as well

2022-04-30 16:26 UTC, ponrajaprabhusk commented on README.md
>  # Technologies used
Done!

2022-04-30 16:26 UTC, ponrajaprabhusk commented on functions/package-lock.json
> -        "firebase-admin": "^10.0.2",
Done

2022-04-30 16:26 UTC, ponrajaprabhusk commented on functions/package.json
> +    "firebase-functions": "^3.19.0"
Done

2022-04-30 16:29 UTC, closed without merging