Fix/task eval reload
Worktez/worktez pull request #603
Opened 2022-06-16 17:53 UTC by sukesh02

### Functionality:
The Drag and drop functionality in Task Evaluation page and Kanban Board

### Solution:
Fixed it using an If statement

### Risk level:
- [x] high 
- [ ] medium
- [ ] low

### How to test:
Now the drag and drop functions without an API error.

2022-06-17 15:14 UTC, sanjaykrishna1203 approved these changes
Approved

2022-06-18 14:45 UTC, viv9k approved these changes
Approved

2022-06-18 14:48 UTC, viv9k requested changes
Please check the required comment

2022-06-18 14:48 UTC, viv9k commented on functions/model/tasks/tark/editTask.js
> +
The best practice would be to handle this milestone issue from UI, better not to send undefined values to backend.

2022-06-18 16:02 UTC, Pendyala-thanvi approved these changes

2022-06-18 17:35 UTC, viv9k requested changes
This might not be a good idea to send milestone as empty string as some tasks might be attached to milestone and therefore If they update anything into the task from task evaluation and kanban board the milestone will be updated to empty string, not a good idea.

Milestone should be attached to previous value of milestone and if there is no previous value for milestone only then send an empty string value.

2022-06-21 15:14 UTC, viv9k approved these changes
Approved

2022-06-22 12:44 UTC, merged