fix(task details):task details bug
Worktez/worktez pull request #604
Opened 2022-06-17 07:45 UTC by Bankar-Swapnil

### Functionality:
fix comment section and log-work functionality
### Solution:
Changes done in task-details component 

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
go to task detail page and comment and log-work and mark task completed without marking log-work 100% and submit it automatically mark completed and on reopen it mark 0%.

2022-06-17 14:05 UTC, Pendyala-thanvi approved these changes

2022-06-17 18:42 UTC, viv9k requested changes
Please do the required fix

2022-06-17 18:42 UTC, viv9k commented on src/app/body/task-details/log-work/log-work.component.html
> +                        <h2>Create New Task</h2>
Create new task for log work???

2022-06-18 08:29 UTC, Bankar-Swapnil commented on src/app/body/task-details/log-work/log-work.component.html
> +                        <h2>Create New Task</h2>
Changes Done

2022-06-18 14:49 UTC, viv9k approved these changes
Approved

2022-06-18 15:03 UTC, merged