fix(labels): 'making labels dynamic'
Worktez/worktez pull request #616
Opened 2022-06-22 17:57 UTC by abhishek-mishra019

Signed-off-by: Abhishek Mishra < am1426620@gmail.com >
### Functionality:
to check and Make the labels dynamic everywhere

### Solution:
made the label calls dynamic everywhere and done some other changes 

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
step 1: check the labels everywhere in the codebase and
step 2: see in dashboard in S no -1 is showing as backlog.
step 3: also check task type label in task details

2022-06-24 16:00 UTC, sanjaykrishna1203 requested changes

2022-06-24 16:00 UTC, sanjaykrishna1203 commented on src/app/body/task-details/task-details.component.ts
> +        console.log(this.task);
Please remove the console logs

2022-06-24 16:00 UTC, sanjaykrishna1203 commented on src/app/icons/generate-icon/generate-icon.component.ts
> +    console.log(this.icon);
Please remove it here too

2022-06-25 16:45 UTC, viv9k approved these changes
Approved

2022-06-25 16:51 UTC, abhishek-mishra019 commented on src/app/body/task-details/task-details.component.ts
> +        console.log(this.task);
resolved

2022-06-25 16:52 UTC, abhishek-mishra019 commented on src/app/icons/generate-icon/generate-icon.component.ts
> +    console.log(this.icon);
resolved

2022-06-25 16:57 UTC, merged