Fixed progress bar in Boards page
Worktez/worktez pull request #628
Opened 2022-07-04 14:35 UTC by muskan2622

### Functionality:
On creating new sprint progress bar was not working.

### Solution:
Now On completing the sprint on the same day its working

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
1. Go to boards page.
2. Create New sprint and mark it as completed.

2022-07-07 03:42 UTC, viv9k requested changes
Please do the required changes

2022-07-07 03:42 UTC, viv9k commented on src/app/body/board/sprint-details/sprint-details.component.ts
> +    console.log(this.today);
remove console.log

2022-07-07 03:42 UTC, viv9k commented on src/app/body/view-organization-details/teams-card/teams-card.component.html
> +                    <span class="material-icons float-right ml-0 mt-2" type="button" (click)="openTeamDetails()" style="cursor: pointer;">settings</span>
These changes are from other PR

2022-07-07 03:42 UTC, viv9k commented on src/app/body/board/sprint-details/sprint-details.component.ts
> +  today: any = new Date();
There is toolsService you can get the dates from there

2022-07-08 14:52 UTC, viv9k commented
change base branch

2022-07-15 15:34 UTC, viv9k requested changes
Please do the required fixed

2022-07-18 12:03 UTC, muskan2622 commented
required fix is done

2022-07-20 10:54 UTC, viv9k approved these changes
Approved

2022-07-22 11:54 UTC, viv9k approved these changes
Approved

2022-07-22 15:54 UTC, merged