fix(filterTask): made the ui fixes in tasks page filter
Worktez/worktez pull request #632
Opened 2022-07-14 09:37 UTC by simran142002

### Functionality:
fixed the filter task in tasks page

### Solution:
made changes in filterTasks component

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve -o
firebase emulators:start

2022-07-14 15:25 UTC, Pendyala-thanvi approved these changes

2022-07-16 14:14 UTC, sanjaykrishna1203 requested changes

2022-07-16 14:14 UTC, sanjaykrishna1203 commented on src/app/body/filter-task/filter-task.component.ts
> +      this.onProjectChange();
What is the Use of Calling this Fuction again when we are calling readTeanData()

2022-07-16 14:14 UTC, sanjaykrishna1203 commented on src/app/body/filter-task/filter-task.component.ts
> +                  this.onProjectChange();
Here too

2022-07-16 15:07 UTC, sanjaykrishna1203 approved these changes
Approved

2022-07-16 15:20 UTC, viv9k approved these changes
Approved

2022-07-16 16:26 UTC, merged