feat(create-post):created add image functionality in create-post
Worktez/worktez pull request #642
Opened 2022-07-26 14:06 UTC by Aditya3034

### Functionality:
Created add image functionality to create-post

### Solution:
Changes in create-post , posts , upload-file service , social-page and librarian components.

### Risk level:
- [X] high 
- [ ] medium
- [ ] low

### How to test:
Steps to test:-
1. open emulator
2. click on create post in Techtag.
3. click on photo and select the image.
4. click on post to post the image in social page.
5. To check the basepath go to firebase storage.

2022-07-28 15:16 UTC, viv9k requested changes
Please do the required fix

2022-07-28 15:16 UTC, viv9k commented on functions/model/librarian/tark/uploadPostImages.js
> +     setPostImages(updateUserFileJson, PostId, imageFileName);
postId should be camel case

2022-07-30 14:32 UTC, viv9k requested changes
Please check properly and update

2022-07-30 14:32 UTC, viv9k commented on src/app/services/fileUploadService/file-upload.service.ts
> +import { Injectable,Input } from '@angular/core';
what is the use of Input?

2022-07-30 14:32 UTC, viv9k commented on src/app/body/view-organization-details/teams-card/teams-card.component.ts
> +  });
Why to change upload team mechanism?

2022-08-07 09:05 UTC, viv9k approved these changes
Approved

2022-08-09 16:45 UTC, Pendyala-thanvi requested changes
Resolve merge conflicts

2022-08-10 10:09 UTC, Pendyala-thanvi approved these changes

2022-08-10 10:09 UTC, merged