Ui fixes done in filter task page
Worktez/worktez pull request #677
Opened 2022-08-22 19:04 UTC by Raisa-12

### Functionality:
Make the UI fixes of filter in dark mode.. Fix there borders, position of custom filter

### Solution:
made changes in filter-tasks.component.css
made changes in filter-tasks.component.html
### Risk level:
- [ ] high 
- [X] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start

2022-08-26 11:44 UTC, Pendyala-thanvi requested changes

2022-08-26 11:44 UTC, Pendyala-thanvi commented on angular.json
> +    "analytics": false
remove these changes

2022-09-02 13:45 UTC, viv9k approved these changes
Approved

2022-09-02 14:28 UTC, Raisa-12 commented
Sure sir

On Fri, 2 Sep, 2022, 7:16 pm Vivek Kumar, ***@***.***> wrote:

> Need demo
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Worktez/worktez/pull/677#issuecomment-1235526225>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU6Z67UWWQUOQPACUOTZAF3V4IALHANCNFSM57IYLMLA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-03 13:43 UTC, Pendyala-thanvi commented
@Raisa-12 resolve merge conflicts

2022-09-03 18:41 UTC, merged