Added Schedular For Subscriptions
Worktez/worktez pull request #732
Opened 2022-09-25 19:32 UTC by Aditya3034

### Functionality:
Added schedular to check Subscription data.
### Solution:
Implemented mechanism to add Schedular which checks the subscriptions data periodically. 
### Risk level:
- [ ] high 
- [X] medium
- [ ] low

### How to test:
1.Open Emulator
2.Use the schedule button in my-dashboard component by Uncommenting it.
3.Check the Firebase logs.
4.You can see the scheduledCheckSub Api executing with no error.
5.You can check Subscription Status changing to Inactive after graceNotification <=0.

2022-09-27 08:50 UTC, sanjaykrishna1203 requested changes
Please do the required changes

2022-09-27 08:50 UTC, sanjaykrishna1203 commented on functions/model/subscriptions/tark/checkSubscription.js
> +      }
you should not assign the comparison data to the subData

2022-09-27 08:50 UTC, sanjaykrishna1203 commented on functions/model/subscriptions/tark/checkSubscription.js
> +      ]
This comparison must be done with the subData and the reference data from application

2022-09-27 08:50 UTC, sanjaykrishna1203 commented on functions/model/subscriptions/tark/checkSubscription.js
> +    const TotalNumberOfMembers = appData.TotalNumberOfMembers;
There is no need for these data here

2022-09-30 14:51 UTC, viv9k requested changes
Need to improve and show a demo after this.

2022-09-30 14:51 UTC, viv9k commented on functions/model/organization/tark/createMember.js
> +     getApplicationData().then((data) => {
This is should be for org not for app

2022-09-30 17:40 UTC, Aditya3034 commented on functions/model/organization/tark/createMember.js
> +     getApplicationData().then((data) => {
did the changes sir.

2022-10-01 05:03 UTC, sanjaykrishna1203 requested changes

2022-10-01 05:03 UTC, sanjaykrishna1203 commented on functions/model/subscriptions/tark/checkSubscription.js
> +      }
This is not needed

2022-10-01 14:07 UTC, Aditya3034 commented on functions/model/subscriptions/tark/checkSubscription.js
> +      }
okay bhaiya

2022-10-01 16:55 UTC, viv9k approved these changes
Approved

2022-10-01 16:59 UTC, merged