Fix(task-details):Fixed Comments Reload
Worktez/worktez pull request #795
Opened 2022-10-27 09:23 UTC by Aditya3034

### Functionality:
Fixed reload issue in task-details comments.

### Solution:
Changes in task-details component.

### Risk level:
- [ ] high 
- [X] medium
- [ ] low

### How to test:
1.Open emulator
2.comment on any task from my-dashboard.
3.comment will be added without reload.

2022-10-27 14:40 UTC, viv9k requested changes
Please do the fix

2022-10-27 14:40 UTC, viv9k commented on src/app/body/task-details/task-details.component.ts
>    async addComment() {
remove async

2022-10-27 15:29 UTC, Pendyala-thanvi approved these changes

2022-10-28 12:52 UTC, sanjaykrishna1203 approved these changes
Approved

2022-10-28 16:12 UTC, viv9k approved these changes
Approved

2022-10-28 17:10 UTC, merged