feat(privateRepoIntegration): private and all repo integration
Worktez/worktez pull request #797
Opened 2022-10-27 14:36 UTC by simran142002

### Functionality:
Now we can integrate even private repos from organization page

### Solution:
added methods for private and all repo links in httpsService

### Risk level:
- [x] high 
- [ ] medium
- [ ] low

### How to test:
ng serve -o
firebase emulators:start

2022-10-27 14:49 UTC, viv9k requested changes
Please improve code quality

2022-10-27 14:49 UTC, viv9k commented on src/app/body/github-link/github-link.component.html
> +                        <ng-container>
no use of ng-container

2022-10-27 14:49 UTC, viv9k commented on src/app/body/github-link/github-link.component.html
> +                                    <button class="btn dropdown-toggle box" type="button" id="button" data-toggle="dropdown" aria-haspopup="true"
style can be moved to css file

2022-10-27 14:49 UTC, viv9k commented on src/app/body/github-link/github-link.component.html
> +                                <input type="text" class="form-control" [(ngModel)]="bearerToken"
move style to css file

2022-10-27 14:49 UTC, viv9k commented on src/app/body/github-link/github-link.component.ts
> +            console.log(data);
remove console.log and subscribe should follow the rule of next, error, complete

2022-10-27 14:49 UTC, viv9k commented on src/app/body/github-link/github-link.component.ts
> +            console.log(data);
remove console.log and subscribe should follow the rule of next, error, complete

2022-10-27 14:49 UTC, viv9k commented on src/app/body/github-link/github-link.component.ts
> +            console.log(data);
remove console.log and subscribe should follow the rule of next, error, complete

2022-10-27 14:49 UTC, viv9k commented on src/app/body/github-link/github-link.component.ts
> +            console.log(data);
remove console.log and subscribe should follow the rule of next, error, complete

2022-10-27 16:44 UTC, Pendyala-thanvi approved these changes

2022-10-28 16:12 UTC, viv9k approved these changes
Approved

2022-10-28 17:09 UTC, merged