Test/git pr details
Worktez/worktez pull request #854
Opened 2022-11-27 03:49 UTC by Aditya3034

### Functionality:
Using this pr for testing of git Pr details

### Solution:
Changes in git & task-details component.
### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### WtId:Dev2

### How to test:

2022-12-01 06:35 UTC, viv9k requested changes
Please do the following changes

2022-12-01 06:35 UTC, viv9k commented on src/app/body/task-details/git/git.component.css
> +    border-radius: 0.3rem;
border radius is always 5px

2022-12-01 06:35 UTC, viv9k commented on src/app/body/task-details/git/git.component.html
> +                        <span class="prBtn btn" (click)="close()">
add class align-middle to span tag

2022-12-01 06:35 UTC, viv9k commented on src/app/body/task-details/git/git.component.css
> +    justify-content: center;
justify center can be removed

2022-12-01 15:03 UTC, Aditya3034 commented
Did the required changes.

2022-12-02 12:56 UTC, viv9k requested changes
please do the required fix

2022-12-02 12:56 UTC, viv9k commented on src/app/body/task-details/task-details.component.css
> +    border-radius: 6px;
border-radius must be 5px

2022-12-03 07:19 UTC, viv9k approved these changes
Approved

2022-12-03 07:29 UTC, merged