Add Team Manager field in update team popup
Worktez/worktez pull request #873
Opened 2022-12-20 11:22 UTC by Bankar-Swapnil

### Functionality:
Add Team Manager field in update team popup

### Solution:
Required changes done

## WtId:
Dev588

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
go to Team-Details Page and click on edit icon

2022-12-21 10:35 UTC, sanjaykrishna1203 requested changes

2022-12-21 10:35 UTC, sanjaykrishna1203 commented on src/app/body/team-details/team-details.component.ts
>    }
Page should not be reloaded
Instead trigger the get functions itself

2022-12-23 05:52 UTC, sanjaykrishna1203 approved these changes
Approved

2022-12-27 15:33 UTC, viv9k approved these changes
Approved

2022-12-27 15:42 UTC, merged